name: Deploy UI to server prod

on:
  workflow_dispatch:
    inputs:
      client_version:
        description: 'Client version'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install package
        run: pnpm install

      - name: Build project
        run: pnpm run build
        env:
          VITE_OAUTH_CLIENT_ID: ${{secrets.VITE_OAUTH_CLIENT_ID_PROD}}
          VITE_GOOGLE_LOGIN_REDIRECT: ${{secrets.VITE_GOOGLE_LOGIN_REDIRECT_PROD}}
          VITE_AUTHORITY_URL: ${{secrets.VITE_AUTHORITY_URL_PROD}}
          VITE_API_BASE_URL: ${{secrets.VITE_API_BASE_URL_PROD}}
          VITE_API_ANT_URL: ${{secrets.VITE_API_ANT_URL_PROD}}
          VITE_MEZON_APP_ID: ${{secrets.VITE_MEZON_APP_ID_PROD}}
          VITE_CLIENT_VERSION: ${{github.event.inputs.client_version}}

      - name: Compress build file
        run: zip -r fe.zip dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: fe-build
          path: fe.zip
          retention-days: 1

  deploy:
    runs-on: w2-fe-prod
    needs:
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: fe-build

      - name: Extract file to server
        run: |
          rm -rf /var/www/app/w2/prod-fe-w2/*
          unzip fe.zip -d /var/www/app/w2/prod-fe-w2/
          rm -rf fe.zip
