name: Deploy UI to server dev

on:
  push:
    branches:
      - develop
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install package
        run: pnpm install

      - name: Build project
        run: pnpm run build
        env: 
          VITE_OAUTH_CLIENT_ID : ${{secrets.VITE_OAUTH_CLIENT_ID}}
          VITE_GOOGLE_LOGIN_REDIRECT : ${{secrets.VITE_GOOGLE_LOGIN_REDIRECT}}
          VITE_AUTHORITY_URL : ${{secrets.VITE_AUTHORITY_URL}}
          VITE_API_BASE_URL : ${{secrets.VITE_API_BASE_URL}}
          VITE_PROXY_SERVER_URL : ${{secrets.VITE_PROXY_SERVER_URL}}
          VITE_API_ANT_URL : ${{secrets.VITE_API_ANT_URL}}
          VITE_MODE : ${{secrets.VITE_MODE}}
          VITE_SENTRY_DSN : ${{secrets.VITE_SENTRY_DSN}}

      - name: Compress build file
        run: zip -r fe.zip dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: fe-build
          path: fe.zip
          retention-days: 1

  deploy:
    runs-on: w2-fe-dev
    needs: 
      - build
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v3
        with:
          name: fe-build

      - name: Extract file to server
        run: |
          rm -rf /apps/ncc-erp-w2/workflow-w2-ui/*
          unzip fe.zip -d /apps/ncc-erp-w2/workflow-w2-ui
          rm -rf fe.zip
  