name: Run Lint and Prettier

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  lint-prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # or your preferred version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run Lint
        run: pnpm run lint

      - name: Run prettier
        run: pnpm run format
