name: Deploy UI to server dev

on:
  push:
    branches:
      - feature/add-var-client-version
      
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy'
        required: true
        default: 'feature/add-var-client-version'
      client_version:
        description: 'Client version'
        required: false
        default: '1.0.0'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install package
        run: pnpm install

      - name: Build project
        run: pnpm run build
        env: 
          VITE_OAUTH_CLIENT_ID : ${{secrets.VITE_OAUTH_CLIENT_ID}}
          VITE_GOOGLE_LOGIN_REDIRECT : ${{secrets.VITE_GOOGLE_LOGIN_REDIRECT}}
          VITE_AUTHORITY_URL : ${{secrets.VITE_AUTHORITY_URL}}
          VITE_API_BASE_URL : ${{secrets.VITE_API_BASE_URL}}
          VITE_PROXY_SERVER_URL : ${{secrets.VITE_PROXY_SERVER_URL}}
          VITE_API_ANT_URL : ${{secrets.VITE_API_ANT_URL}}
          VITE_MODE : ${{secrets.VITE_MODE}}
          VITE_CLIENT_VERSION: ${{ github.event.inputs.client_version }}

      - name: Compress build file
        run: echo "VITE_CLIENT_VERSION=${{ github.event.inputs.client_version }}""