name: Run Tests

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  tests:
    runs-on: ubuntu-latest

    #grant permissions for token git
    permissions:
      pull-requests: write
      issues: write
      contents: read
      packages: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # or your preferred version

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run tests
        run: pnpm run test --no-cache

      - name: Post coverage comment to pull request
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

          script: |
            const fs = require('fs');

            const coverageContent = fs.readFileSync('./src/tests/coverage/coverage.txt', 'utf-8');

            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: 'Code Coverage Results:\n\n```\n' + coverageContent + '\n```\n',
            });
